### ISSUE TITLE
Update to edition 2021

### ISSUE THREAD

**Issue by jhbabon** [jhbabon/scout#12]
Update `Cargo.toml` with:

```toml
[package]
edition = "2021"
rust-version = "1.56"
```

* https://blog.rust-lang.org/2021/10/21/Rust-1.56.0.html
* https://doc.rust-lang.org/edition-guide/editions/transitioning-an-existing-project-to-a-new-edition.html
